version: '3'
services:
  nagios_dev:
    image: nagios:dev
    environment:
    - NAGIOS_FQDN=monitoring.local
    - MAIL_RELAY_HOST=[127.0.0.1]:1025
    - NAGIOS_TIMEZONE=Europe/Zurich
    - PHP_UPLOAD_MAX_FILESIZE=25M
    - PHP_POST_MAX_SIZE=25M
    volumes:
    - $PWD/dev_data/etc:/opt/nagios/etc
#    - $PWD/dev_data/var:/opt/nagios/var
    - $PWD/dev_data/plugins:/opt/plugins
    - $PWD/dev_data/scripts:/opt/scripts
    ports:
    - 8086:80
    - 8026:8025