version: '3'
services:
  nagios:
    build: .
    environment:
    - NAGIOS_TIMEZONE=Europe/Zurich
    volumes:
    - $PWD/data/etc:/opt/nagios/etc
    - $PWD/data/plugins:/opt/plugins
    - $PWD/data/scripts:/opt/scripts
    - $PWD/data/graph:/opt/nagiosgraph/etc
    ports:
    - 8085:80
    - 8025:8025
    - 1025:1025
    - 137:22
    restart: unless-stopped